#ifndef EXTRACTTEXT_APP_INTERFACE_BACKGROUND_PROBABILITY_PROBABILITY_STRUCT_H_
#define EXTRACTTEXT_APP_INTERFACE_BACKGROUND_PROBABILITY_PROBABILITY_STRUCT_H_

enum ProbabilityOperation
{
    OP_COUNTING
};

enum ProbabilityTerminologies
{
    VENN_DIAGRAM
};

#endif